### PR TITLE
“Speedup” and "slowdown" are dictionary words, and other edits.

### PR DESCRIPTION
**Pull request by StevenBlack**
If merged, this PR changes `speed-up` to `speedup` everywhere.

Ref:
* https://www.merriam-webster.com/dictionary/speedup and also 
* https://en.wikipedia.org/wiki/Speedup.

### CODE REVIEW

**Comment by nnethercote** [comment]
We should probably also change "slow-down" to "slowdown"... would you like to add that?

**Comment by StevenBlack** [comment]
Yes, I'll do that.

**Comment by StevenBlack** [comment]
Guys sorry for the commit-explosion here, I botched the resolution of a three-way merge-conflict.

**Comment by nnethercote** [comment]
This ended up in a non-mergeable state, so I did the dehyphenation myself in [f0a1c66](https://github.com/nnethercote/perf-book/commit/f0a1c66d715550fc27fa45b6f73ea550361c84d8). Thanks for the idea.

**Pull request closed without merging**
