### PR TITLE
Mention mold linker

### PR DESCRIPTION
**Pull request by sigmaSd**
Mold repo: https://github.com/rui314/

### CODE REVIEW

**Comment by sigmaSd** [comment]
I personally use https://gitpod.io/ to compile it from source, I'm not sure if this is something that is worth mentioning?

**Comment by nnethercote** [comment]
I definitely want to mention mold, but I also want to try it out myself first to make sure I'm writing reasonable things. That explains the slow response here -- finding the time to investigate (sorry!)

**Comment by sigmaSd** [comment]
Thats reasonable of course, some distro (like arch Linux) are now packaging mold officialy so it should be easier to use

**Comment by nnethercote** [comment]
I finally got around to this: https://github.com/nnethercote/perf-book/commit/dc7b0d7c707c9a1a45c58aeb771b463e3672dfff

Thanks for the suggestion!

**Pull request closed without merging**
